import { Pagination } from '@/components/pagination/Pagination'
import { DisplayData } from '@/features/characters/DisplayData'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Rick And Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DisplayData />
      <Pagination />
    </>
  )
}
